//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDept
    {
        public float id { get; set; }
        public float id_emp { get; set; }
        public string card_no { get; set; }
        public string dept { get; set; }
    }
}
